
# 서버 포트번호 설정
server:
  port: 80
  
spring:
# SMTP - 메일 보내기 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: developtest0122@naver.com
    password: DEVELOPtest0724@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# JPA 설정
  jpa:
    properties:
      hibernate:
        format_sql:true
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      
# DB 접속을 위한 정보 설정      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oral_care
    username: root
    password: root

# jsp파일 설정    
  mvc:
    # static 보이도록 설정
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp